name: geodesytsc
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pyproj
  - pandas
  - jupyterlab
  - ipympl
  - meshio
  - tqdm
  - h5py
  - cutde
  - polars
  - pyarrow
  - scipy
  - altair
  - vegafusion 
  - vl-convert-python
  - xarray
  - h5netcdf
  - pip
  - pip:
      - gmsh
      - earthscope-sdk
